name: CI
on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v2
      - name: use nodeJS
        uses: actions/setpup-node@v1
        with:
         node-version: "12.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true   
  